"""empty message

Revision ID: 6d2b17dd1723
Revises: e0cd9895cfba
Create Date: 2022-05-10 01:08:35.299763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2b17dd1723'
down_revision = 'e0cd9895cfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('speed', sa.String(length=120), nullable=False),
    sa.Column('weapons', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('galaxy', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.String(length=120), nullable=False),
    sa.Column('shine_color', sa.String(length=120), nullable=False),
    sa.Column('distance_from_sun', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distance_from_sun'),
    sa.UniqueConstraint('distance_from_sun'),
    sa.UniqueConstraint('galaxy'),
    sa.UniqueConstraint('galaxy'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('shine_color'),
    sa.UniqueConstraint('shine_color')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stars')
    op.drop_table('Ships')
    # ### end Alembic commands ###
