"""empty message

Revision ID: e0cd9895cfba
Revises: 44eda26fb1b3
Create Date: 2022-05-10 00:21:40.029704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0cd9895cfba'
down_revision = '44eda26fb1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('distance_from_sun', table_name='Stars')
    op.drop_index('distance_from_sun_2', table_name='Stars')
    op.drop_index('galaxy', table_name='Stars')
    op.drop_index('galaxy_2', table_name='Stars')
    op.drop_index('mass', table_name='Stars')
    op.drop_index('mass_2', table_name='Stars')
    op.drop_index('name', table_name='Stars')
    op.drop_index('name_2', table_name='Stars')
    op.drop_index('shine_color', table_name='Stars')
    op.drop_index('shine_color_2', table_name='Stars')
    op.drop_table('Stars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stars',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('galaxy', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('mass', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('shine_color', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('distance_from_sun', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('shine_color_2', 'Stars', ['shine_color'], unique=False)
    op.create_index('shine_color', 'Stars', ['shine_color'], unique=False)
    op.create_index('name_2', 'Stars', ['name'], unique=False)
    op.create_index('name', 'Stars', ['name'], unique=False)
    op.create_index('mass_2', 'Stars', ['mass'], unique=False)
    op.create_index('mass', 'Stars', ['mass'], unique=False)
    op.create_index('galaxy_2', 'Stars', ['galaxy'], unique=False)
    op.create_index('galaxy', 'Stars', ['galaxy'], unique=False)
    op.create_index('distance_from_sun_2', 'Stars', ['distance_from_sun'], unique=False)
    op.create_index('distance_from_sun', 'Stars', ['distance_from_sun'], unique=False)
    # ### end Alembic commands ###
